workflows:
  ios-workflow:
    name: VCMI iOS Build
    environment:
      xcode: latest # Используем последнюю поддерживаемую версию
      cocoapods: default
    scripts:
      - name: Install system dependencies
        script: |
          brew install \
            autoconf \
            automake \
            libtool \
            pkg-config \
            cmake \
            gettext \
            ninja

      - name: Clone VCMI
        script: |
          git clone --recursive https://github.com/vcmi/vcmi.git
          cd vcmi

      - name: Configure for iOS
        script: |
          cd vcmi
          mkdir -p build-ios
          cd build-ios

          # Определяем минимальную версию iOS
          export IOS_DEPLOYMENT_TARGET=10.0
          
          # Получаем путь к SDK
          export SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          export SDK_VERSION=$(xcrun --sdk iphoneos --show-sdk-version)

          echo "Using iOS SDK: $SDK_PATH"
          echo "SDK Version: $SDK_VERSION"

      - name: Build dependencies
        script: |
          cd vcmi/build-ios
          
          # Конфигурация CMake для iOS
          cmake .. \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=$IOS_DEPLOYMENT_TARGET \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_TEST=OFF \
            -DENABLE_LAUNCHER=OFF \
            -DENABLE_EDITOR=OFF \
            -DCMAKE_INSTALL_PREFIX=../install-ios

      - name: Build VCMI
        script: |
          cd vcmi/build-ios
          
          # Компиляция проекта
          cmake --build . --config Release --parallel $(sysctl -n hw.ncpu)

      - name: Create IPA package
        script: |
          cd vcmi/build-ios
          
          # Создание директории для .ipa
          mkdir -p Payload
          
          # Поиск и копирование .app bundle
          APP_BUNDLE=$(find . -name "*.app" -type d | head -1)
          if [ -z "$APP_BUNDLE" ]; then
            echo "Error: No .app bundle found!"
            find . -name "*.app" -type d
            exit 1
          fi
          
          echo "Found app bundle: $APP_BUNDLE"
          cp -r "$APP_BUNDLE" Payload/
          
          # Создание .ipa без подписи
          zip -r vcmi-ios-unsigned.ipa Payload
          
          # Перемещение .ipa в корень проекта
          mv vcmi-ios-unsigned.ipa $CM_BUILD_DIR/

    artifacts:
      - vcmi-ios-unsigned.ipa
      - vcmi/build-ios/**/*.app

    publishing:
      email:
        recipients:
          - user@example.com # Замените на ваш email