workflows:
  vcmi-ios-workflow:
    name: VCMI iOS Simple Build
    environment:
      cocoapods: default
    scripts:
      - name: Install dependencies and explore
        script: |
          git clone --recursive https://github.com/vcmi/vcmi.git
          cd vcmi
          
          # Исследуем структуру проекта
          echo "=== Project structure ==="
          find . -name "CMakeLists.txt" | head -10
          find . -name "*.xcodeproj" -o -name "*.xcworkspace" | head -10
          
          # Проверяем, есть ли готовые решения для iOS
          if [ -f "ios/CMakeLists.txt" ]; then
            echo "Found iOS CMakeLists.txt"
            cat ios/CMakeLists.txt
          fi

      - name: Try Xcode build
        script: |
          cd vcmi
          # Пробуем найти Xcode проект
          if [ -d "ios/vcmi.xcodeproj" ]; then
            xcodebuild -project ios/vcmi.xcodeproj \
              -scheme vcmi \
              -configuration Release \
              -sdk iphoneos \
              IPHONEOS_DEPLOYMENT_TARGET=10.0 \
              CODE_SIGNING_ALLOWED=NO \
              CODE_SIGN_IDENTITY="" \
              build
          else
            echo "No Xcode project found. Available projects:"
            find . -name "*.xcodeproj" -type d
          fi

      - name: Package results
        script: |
          cd vcmi
          # Ищем собранное приложение
          APP_PATH=$(find . -name "*.app" -type d | grep -i release | head -1)
          if [ -z "$APP_PATH" ]; then
            APP_PATH=$(find . -name "*.app" -type d | head -1)
          fi
          
          if [ -n "$APP_PATH" ]; then
            mkdir -p Payload
            cp -r "$APP_PATH" Payload/
            zip -r vcmi-ios-unsigned.ipa Payload
            mv vcmi-ios-unsigned.ipa $CM_BUILD_DIR/
          else
            echo "No .app bundle found for packaging"
            find . -name "*.app" -type d
          fi

    artifacts:
      - vcmi-ios-unsigned.ipa
      - vcmi/**/*.app