workflows:
  ios-workflow:
    name: VCMI iOS Build
    environment:
      xcode: 14.2 # Xcode версии, которая поддерживает iOS 10
      cocoapods: default
    scripts:
      - name: Install system dependencies
        script: |
          brew install \
            autoconf \
            automake \
            libtool \
            pkg-config \
            cmake \
            gettext \
            ninja

      - name: Clone VCMI
        script: |
          git clone --recursive https://github.com/vcmi/vcmi.git
          cd vcmi

      - name: Build dependencies
        script: |
          cd vcmi
          mkdir -p build-ios
          cd build-ios

          # Установка переменных для iOS кросс-компиляции
          export IOS_VERSION_MIN=10.0
          export IOS_SDK_VERSION=$(xcrun --sdk iphoneos --show-sdk-version)
          export IOS_CMAKE_FLAGS="\
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=$IOS_VERSION_MIN \
            -DCMAKE_IOS_INSTALL_COMBINED=YES \
            -DCMAKE_INSTALL_PREFIX=../install-ios \
            -DCMAKE_BUILD_TYPE=Release"

          # Сборка зависимостей
          cmake .. $IOS_CMAKE_FLAGS \
            -DENABLE_TEST=OFF \
            -DENABLE_LAUNCHER=OFF \
            -DENABLE_EDITOR=OFF \
            -DENABLE_PCH=OFF

      - name: Build VCMI
        script: |
          cd vcmi/build-ios
          
          # Компиляция проекта
          cmake --build . --config Release --parallel $(sysctl -n hw.ncpu)

      - name: Create IPA
        script: |
          cd vcmi/build-ios
          
          # Создание структуры .ipa
          mkdir -p Payload
          cp -r bin/Release/*.app Payload/
          
          # Создание .ipa без подписи
          zip -r vcmi-ios-unsigned.ipa Payload
          
          # Перемещение .ipa в корень проекта
          mv vcmi-ios-unsigned.ipa $CM_BUILD_DIR/

    artifacts:
      - vcmi-ios-unsigned.ipa
      - vcmi/build-ios/bin/Release/*.app

    publishing:
      email:
        recipients:
          - user@example.com # Замените на ваш email