workflows:
  build-vcmi-ios:
    name: Build VCMI iOS (Release)
    max_build_duration: 120
    environment:
      xcode: latest
      vars:
        BUILD_PRESET: "ios-release-conan"
        BUILD_TYPE: "Release"
        BUNDLE_IDENTIFIER_PREFIX: "com.example"
        DEVELOPMENT_TEAM: ""
        APP_NAME: "VCMI"
    scripts:
      - name: Install dependencies
        script: |
          brew install cmake conan ccache
          conan profile detect --force
          # Conan home cache fix for Codemagic
          mkdir -p ~/.conan2
          echo "Detected Conan profile:"
          cat ~/.conan2/profiles/default || true

      - name: Configure project with CMake preset
        script: |
          cmake --preset $BUILD_PRESET \
            -D BUNDLE_IDENTIFIER_PREFIX=$BUNDLE_IDENTIFIER_PREFIX \
            -D CMAKE_BUILD_TYPE=$BUILD_TYPE \
            -D ENABLE_CCACHE=ON

      - name: Build VCMI via CMake
        script: |
          cmake --build build-$BUILD_PRESET --target vcmiclient -- -quiet

      - name: Package IPA using CPack
        script: |
          cd build-$BUILD_PRESET
          cpack -C Release || true
          # Rename zip to ipa if necessary
          if [ -f *.zip ]; then
            ZIPFILE=$(ls *.zip | head -n 1)
            mv "$ZIPFILE" "${ZIPFILE%.zip}.ipa"
          fi

    artifacts:
      - build-ios-release-conan/*.ipa
      - build-ios-release-conan/*.zip

    publishing:
      email:
        recipients:
          - your_email@example.com
